### ISSUE TITLE
Toggle checked emblem not working

### ISSUE THREAD

**Issue by rootwork** [smurphos/nemo_actions_and_cinnamon_scripts#14]
Thanks for this great collection of actions! I have several installed and working.

However, I couldn't get "Toggle Check" to work. I tried installing it twice just to be sure.

I get the "Toggle Check" action listed in the context menu, and if I use it on an item it does seem to update the icon -- the file modification date changes, and in some cases there's a brief "loading" icon that appears. But when the icon reloads, there's no actual checkbox visible.

Tried in both icon view and list view.

version info:
Linux Mint 20.1 (Ubuntu Focal)
Nemo 4.8.6

**Comment by Shaolin-Twelve** [comment]
I too had issues with "Toggle Check", it would remove any emblem already present, but wouldn't add one back when there is no emblem, and it doesn't work at all with multiple files or folders selected, only single files or folders.

I got around the single toggle issue by altering the toggle_checked.sh script at line 5, to read 'metadata::emblems default' at the end of line 5, instead of where it read 'metadata::emblems emblem-checked' previously on line 5.

For me I want to be able to mark multiple selected files and folders with the default check tick emblem, however while I can now toggle the default check tick on single items, the action disappears on multiple file or folder selections, and even running the script using the Scripts context menu item fails to add/remove the default emblem to multiple selections.

Linux Mint 20
Nemo 4.6.5

**Comment by smurphos** [comment]
Apologies both for delayed response - there's been a typo lurking in this action since day 1 - now fixed and script updated to allow for multiple selections with https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/commit/854f20f4d9c269c43289cfafb0a0e4dd736d2543

Also icon name changed to emblem-default as emblem-check isn't extant in all icon themes.
https://github.com/smurphos/nemo_actions_and_cinnamon_scripts/commit/29c3c1002f4578d8012bc47bf8923ac1741ffa36
